apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-task-api
spec:
  selector:
    app: task-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
